name: Mogeko`s Blog
on: push

env:
  GH_USERNAME: Mogeko
  GH_EMAIL: zhengjunyi@live.com
  GH_REPO: github.com/Mogeko/mogeko.github.io
  GH_BRANCH: master

jobs:
  linter:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter/slim@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_JSCPD: false
          DEFAULT_BRANCH: master
          MARKDOWN_CONFIG_FILE: .markdownlint.json
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
          submodules: true
          fetch-depth: 1
    - name: Build site
      uses: jakejarvis/hugo-build-action@master
      with:
        args: --minify
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: site
        path: public

  deploy:
    needs: [build, linter]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
          fetch-depth: 1
    - name: Download Artifact
      uses: actions/download-artifact@v2
      with:
        name: site
    - name: Deploy to GitHub
      uses: JamesIves/github-pages-deploy-action@4.1.5
      with:
        folder: .
        branch: ${GH_BRANCH}
        token: ${{ secrets.DEPLOY_TOKEN }}
        git-config-name: ${GH_USERNAME}
        git-config-email: ${GH_EMAIL}
        repository-name: ${GH_REPO}
        single-commit: true
